# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20180409_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
    ]
